/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/monitors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Monitors */
        get: operations["list_monitors_monitors_get"];
        put?: never;
        /** Create Monitor */
        post: operations["create_monitor_monitors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitors/{monitor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Monitor */
        get: operations["get_monitor_monitors__monitor_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Monitor */
        patch: operations["update_monitor_monitors__monitor_id__patch"];
        trace?: never;
    };
    "/monitors/{monitor_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_monitors__monitor_id__runs_get"];
        put?: never;
        /** Trigger Run */
        post: operations["trigger_run_monitors__monitor_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description Requirement 5: a client polls a run id and sees the stage reached and
         *     whether it succeeded, was partial, or failed.
         */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Stats
         * @description Requirement 5: each source's outcome while a run is in flight — the
         *     other half of `RunProgress` alongside `GET /runs/{id}` (design.md,
         *     "Domain shapes").
         */
        get: operations["get_run_stats_runs__run_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitors/{monitor_id}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_monitors__monitor_id__sources_get"];
        put?: never;
        /** Attach Source */
        post: operations["attach_source_monitors__monitor_id__sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Source */
        patch: operations["update_source_sources__source_id__patch"];
        trace?: never;
    };
    "/monitors/{monitor_id}/overrides/retention-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview Retention */
        get: operations["preview_retention_monitors__monitor_id__overrides_retention_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitors/{monitor_id}/overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Overrides */
        get: operations["list_overrides_monitors__monitor_id__overrides_get"];
        put?: never;
        /** Submit Override */
        post: operations["submit_override_monitors__monitor_id__overrides_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitors/{monitor_id}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Overview */
        get: operations["get_overview_monitors__monitor_id__overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitors/{monitor_id}/timeseries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Timeseries */
        get: operations["get_timeseries_monitors__monitor_id__timeseries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitors/{monitor_id}/topics/ranking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Topic Ranking */
        get: operations["get_topic_ranking_monitors__monitor_id__topics_ranking_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitors/{monitor_id}/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Entity Comparison */
        get: operations["get_entity_comparison_monitors__monitor_id__compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitors/{monitor_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_monitors__monitor_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitors/{monitor_id}/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Insights */
        get: operations["list_insights_monitors__monitor_id__insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/insights/{insight_id}/judgement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Judgement
         * @description Requirement 6: a user marks an opportunity useful or not, recorded
         *     against an existing insight — untrusted feedback validated at this
         *     boundary as a reference to a real row (design.md, "Trust boundary").
         */
        post: operations["record_judgement_insights__insight_id__judgement_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitors/{monitor_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browse Documents */
        get: operations["browse_documents_monitors__monitor_id__documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitors/{monitor_id}/alert-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Alert Rules */
        get: operations["list_alert_rules_monitors__monitor_id__alert_rules_get"];
        put?: never;
        /** Create Alert Rule */
        post: operations["create_alert_rule_monitors__monitor_id__alert_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Absence
         * @description Requirement 6 made into a type: four situations that must not all
         *     collapse into an empty list (learn.md, "Empty, absent, and unknown").
         * @enum {string}
         */
        Absence: "no_data" | "unknown_topic" | "unknown_source" | "out_of_retention";
        /** AlertRuleCreateRequest */
        AlertRuleCreateRequest: {
            kind: components["schemas"]["ReadAlertKind"];
            /**
             * Conditions
             * @default {}
             */
            conditions: {
                [key: string]: unknown;
            };
            channel: components["schemas"]["Channel"];
            /** Target */
            target: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /** AlertRuleResponse */
        AlertRuleResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Monitor Id
             * Format: uuid
             */
            monitor_id: string;
            kind: components["schemas"]["ReadAlertKind"];
            /** Conditions */
            conditions: {
                [key: string]: unknown;
            };
            channel: components["schemas"]["Channel"];
            /** Target */
            target: string;
            /** Enabled */
            enabled: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * Channel
         * @enum {string}
         */
        Channel: "email" | "webhook";
        /** DataQuality */
        DataQuality: {
            /** Sample Size */
            sample_size: number;
            /** Truncated Days */
            truncated_days: string[];
            /** Sources Ok */
            sources_ok: components["schemas"]["SourceName"][];
            /** Sources Failed */
            sources_failed: components["schemas"]["SourceName"][];
            /** Topics Absent */
            topics_absent: string[];
        };
        /** DateRange */
        DateRange: {
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
        };
        /** DocumentPage */
        DocumentPage: {
            /** Items */
            items: components["schemas"]["DocumentView"][];
            /** Cursor */
            cursor: string | null;
            /** Total Known */
            total_known: number | null;
        };
        /** DocumentView */
        DocumentView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            source_name: components["schemas"]["SourceName"];
            /** Url */
            url: string | null;
            /** Body */
            body: string | null;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Rating */
            rating: number | null;
            /** Topic Id */
            topic_id: string | null;
        };
        /** EntityComparison */
        EntityComparison: {
            period: components["schemas"]["DateRange"];
            /** Entries */
            entries: components["schemas"]["EntityComparisonRow"][];
            data_quality: components["schemas"]["DataQuality"];
        };
        /** EntityComparisonRow */
        EntityComparisonRow: {
            /** Entity Id */
            entity_id: string;
            /** Doc Count */
            doc_count: number;
            /** Share Of Voice */
            share_of_voice: number;
            /** Sentiment Mean */
            sentiment_mean: number | null;
        };
        /**
         * EventKind
         * @description What a user sees. Kept separate from ``Method`` (design.md, "Domain
         *     shapes") — a burst found by two methods is still one kind a user can
         *     filter their feed on.
         * @enum {string}
         */
        EventKind: "burst" | "sustained_growth" | "decline" | "sentiment_flip" | "changepoint" | "emergence" | "novelty";
        /** EventView */
        EventView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Topic Id
             * Format: uuid
             */
            topic_id: string;
            /**
             * Detected On
             * Format: date
             */
            detected_on: string;
            kind: components["schemas"]["EventKind"];
            /** Method */
            method: string;
            /** Severity */
            severity: number;
            /** Statistics */
            statistics: {
                [key: string]: unknown;
            };
            /** Evidence Ids */
            evidence_ids: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InsightKind
         * @enum {string}
         */
        InsightKind: "digest" | "opportunity";
        /** InsightView */
        InsightView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Monitor Id
             * Format: uuid
             */
            monitor_id: string;
            /** Topic Id */
            topic_id: string | null;
            period: components["schemas"]["DateRange"];
            kind: components["schemas"]["InsightKind"];
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Who */
            who: string | null;
            /** What */
            what: string | null;
            /** Why */
            why: string | null;
            /** Score */
            score: number | null;
            /** Score Components */
            score_components: {
                [key: string]: number;
            };
            /** Evidence Ids */
            evidence_ids: string[];
            /** Llm Provider */
            llm_provider: string;
            /** Llm Model */
            llm_model: string;
            /** Prompt Version */
            prompt_version: string;
        };
        /** JudgementRequest */
        JudgementRequest: {
            /** Useful */
            useful: boolean;
        };
        /**
         * Metric
         * @enum {string}
         */
        Metric: "volume" | "prevalence" | "sentiment" | "engagement" | "author_diversity" | "rating";
        /** MonitorCreateRequest */
        MonitorCreateRequest: {
            /** Name */
            name: string;
            target_type: components["schemas"]["TargetType"];
            /** Seed */
            seed: {
                [key: string]: unknown;
            };
            /** Cron Expression */
            cron_expression: string;
            /** Timezone */
            timezone: string;
            /** Retention Days */
            retention_days: number;
        };
        /** MonitorResponse */
        MonitorResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            target_type: components["schemas"]["TargetType"];
            /** Seed */
            seed: {
                [key: string]: unknown;
            };
            /** Cron Expression */
            cron_expression: string;
            /** Timezone */
            timezone: string;
            status: components["schemas"]["MonitorStatus"];
            /** Retention Days */
            retention_days: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Projected */
            projected: boolean;
        };
        /** MonitorSourceCreateRequest */
        MonitorSourceCreateRequest: {
            source_name: components["schemas"]["SourceName"];
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Daily Quota */
            daily_quota: number;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /** MonitorSourceResponse */
        MonitorSourceResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Monitor Id
             * Format: uuid
             */
            monitor_id: string;
            source_name: components["schemas"]["SourceName"];
            /** Instance Key */
            instance_key: string;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Daily Quota */
            daily_quota: number;
            /** Enabled */
            enabled: boolean;
            /** Last External Id */
            last_external_id: string | null;
            /** Last Published At */
            last_published_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** MonitorSourceUpdateRequest */
        MonitorSourceUpdateRequest: {
            /** Daily Quota */
            daily_quota?: number | null;
            /** Enabled */
            enabled?: boolean | null;
        };
        /**
         * MonitorStatus
         * @description A monitor's lifecycle. There is no terminal success state (handoff §1.2).
         * @enum {string}
         */
        MonitorStatus: "active" | "paused" | "archived";
        /** MonitorUpdateRequest */
        MonitorUpdateRequest: {
            /** Name */
            name?: string | null;
            /** Seed */
            seed?: {
                [key: string]: unknown;
            } | null;
            /** Cron Expression */
            cron_expression?: string | null;
            /** Timezone */
            timezone?: string | null;
            /** Retention Days */
            retention_days?: number | null;
            /** Status */
            status?: ("active" | "paused" | "archived") | null;
        };
        /** OverrideJobView */
        OverrideJobView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Monitor Id
             * Format: uuid
             */
            monitor_id: string;
            kind: components["schemas"]["OverrideKind"];
            /** Parameters */
            parameters: {
                [key: string]: unknown;
            };
            status: components["schemas"]["OverrideStatus"];
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Outcome */
            outcome: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * OverrideKind
         * @enum {string}
         */
        OverrideKind: "stage_rerun" | "backfill_window" | "retention_purge";
        /** OverrideRequest */
        OverrideRequest: {
            kind: components["schemas"]["OverrideKind"];
            stage?: components["schemas"]["Stage"] | null;
            /** Window Start */
            window_start?: string | null;
            /** Window End */
            window_end?: string | null;
            /** Purge Token */
            purge_token?: string | null;
        };
        /**
         * OverrideStatus
         * @description ``PARTIAL`` is a first-class outcome, not a failure: a backfill window
         *     where one date failed did the rest of the work honestly (design.md,
         *     "Domain shapes").
         * @enum {string}
         */
        OverrideStatus: "pending" | "running" | "complete" | "partial" | "failed";
        /** OverrideSubmitResponse */
        OverrideSubmitResponse: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
        };
        /** Overview */
        Overview: {
            period: components["schemas"]["DateRange"];
            /** Headline Figures */
            headline_figures: {
                [key: string]: number | null;
            };
            data_quality: components["schemas"]["DataQuality"];
        };
        /**
         * PointQuality
         * @enum {string}
         */
        PointQuality: "clean" | "truncated" | "partial";
        /**
         * ReadAlertKind
         * @description Distinct from ``AlertKind`` (scraper health) — a rule for one must not
         *     match the other (requirements.md, requirement 8; design.md, "Alternatives":
         *     "One alert rule table matching both kinds by a condition").
         * @enum {string}
         */
        ReadAlertKind: "product" | "scraper";
        /** RetentionPreviewResponse */
        RetentionPreviewResponse: {
            /** Count */
            count: number;
            /** Token */
            token: string;
        };
        /**
         * RunSourceStatsView
         * @description One source's outcome within a run, for the progress panel's poll
         *     (on-demand-collection design.md, "Domain shapes": `RunProgress`).
         */
        RunSourceStatsView: {
            /**
             * Monitor Source Id
             * Format: uuid
             */
            monitor_source_id: string;
            /** Attempted */
            attempted: number;
            /** Fetched */
            fetched: number;
            /** Kept */
            kept: number;
            /** Quota */
            quota: number;
            /** Quota Outcome */
            quota_outcome: string;
            /** Validation Failed */
            validation_failed: boolean;
            /** Error */
            error: string | null;
        };
        /** RunSummaryView */
        RunSummaryView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Run Date
             * Format: date
             */
            run_date: string;
            /** Status */
            status: string;
            /** Is Backfill */
            is_backfill: boolean;
        };
        /** RunTriggerRequest */
        RunTriggerRequest: {
            /** Run Date */
            run_date?: string | null;
            /**
             * Is Backfill
             * @default false
             */
            is_backfill: boolean;
        };
        /** RunTriggerResponse */
        RunTriggerResponse: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /** RunView */
        RunView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Monitor Id
             * Format: uuid
             */
            monitor_id: string;
            /**
             * Run Date
             * Format: date
             */
            run_date: string;
            /** Status */
            status: string;
            /** Stage Status */
            stage_status: {
                [key: string]: string;
            };
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /** Series */
        Series: {
            metric: components["schemas"]["Metric"];
            /** Topic Id */
            topic_id: string | null;
            source: components["schemas"]["SourceName"] | null;
            /** Points */
            points: components["schemas"]["SeriesPoint"][];
            absence: components["schemas"]["Absence"] | null;
            data_quality: components["schemas"]["DataQuality"];
        };
        /** SeriesPoint */
        SeriesPoint: {
            /**
             * Bucket
             * Format: date
             */
            bucket: string;
            /** Value */
            value: number | null;
            quality: components["schemas"]["PointQuality"];
        };
        /**
         * SourceName
         * @description Which adapter a source row is collected by. Closed: only what is built.
         * @enum {string}
         */
        SourceName: "play" | "appstore" | "discourse" | "news" | "rss" | "hackernews";
        /**
         * Stage
         * @enum {string}
         */
        Stage: "clean" | "language" | "relevance" | "duplicate" | "embed" | "sentiment" | "intent";
        /**
         * TargetType
         * @description What a monitor watches. Closed: seed validation depends on knowing which.
         * @enum {string}
         */
        TargetType: "product" | "theme";
        /** TopicRanking */
        TopicRanking: {
            /** Entries */
            entries: components["schemas"]["TopicRankingEntry"][];
            data_quality: components["schemas"]["DataQuality"];
        };
        /** TopicRankingEntry */
        TopicRankingEntry: {
            /**
             * Topic Id
             * Format: uuid
             */
            topic_id: string;
            /** Label */
            label: string;
            /** Doc Count */
            doc_count: number;
            /** Doc Count Share */
            doc_count_share: number;
            /** Sentiment Mean */
            sentiment_mean: number | null;
            /** Trend Score */
            trend_score: number | null;
            /** Breadth Ratio */
            breadth_ratio: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_monitors_monitors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorResponse"][];
                };
            };
        };
    };
    create_monitor_monitors_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonitorCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_monitor_monitors__monitor_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monitor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_monitor_monitors__monitor_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monitor_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonitorUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_monitors__monitor_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monitor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummaryView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_run_monitors__monitor_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monitor_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunTriggerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunTriggerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_stats_runs__run_id__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSourceStatsView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_monitors__monitor_id__sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monitor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorSourceResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attach_source_monitors__monitor_id__sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monitor_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonitorSourceCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorSourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_source_sources__source_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonitorSourceUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorSourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_retention_monitors__monitor_id__overrides_retention_preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monitor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetentionPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_overrides_monitors__monitor_id__overrides_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monitor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverrideJobView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_override_monitors__monitor_id__overrides_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monitor_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverrideRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverrideSubmitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_overview_monitors__monitor_id__overview_get: {
        parameters: {
            query: {
                start: string;
                end: string;
            };
            header?: never;
            path: {
                monitor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_timeseries_monitors__monitor_id__timeseries_get: {
        parameters: {
            query: {
                metric: components["schemas"]["Metric"];
                start: string;
                end: string;
                topic_id?: string | null;
                source?: components["schemas"]["SourceName"] | null;
            };
            header?: never;
            path: {
                monitor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Series"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_topic_ranking_monitors__monitor_id__topics_ranking_get: {
        parameters: {
            query: {
                start: string;
                end: string;
            };
            header?: never;
            path: {
                monitor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicRanking"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_entity_comparison_monitors__monitor_id__compare_get: {
        parameters: {
            query: {
                start: string;
                end: string;
            };
            header?: never;
            path: {
                monitor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityComparison"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_monitors__monitor_id__events_get: {
        parameters: {
            query: {
                start: string;
                end: string;
            };
            header?: never;
            path: {
                monitor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_insights_monitors__monitor_id__insights_get: {
        parameters: {
            query: {
                start: string;
                end: string;
                kind?: components["schemas"]["InsightKind"] | null;
            };
            header?: never;
            path: {
                monitor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_judgement_insights__insight_id__judgement_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                insight_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JudgementRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    browse_documents_monitors__monitor_id__documents_get: {
        parameters: {
            query?: {
                topic_id?: string | null;
                source?: components["schemas"]["SourceName"] | null;
                start?: string | null;
                end?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                monitor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alert_rules_monitors__monitor_id__alert_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monitor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRuleResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_alert_rule_monitors__monitor_id__alert_rules_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monitor_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRuleCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRuleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
