"""add enrichment table

Revision ID: 652958fbb901
Revises: 54234fafb85a
Create Date: 2026-08-20 03:19:48.405935+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '652958fbb901'
down_revision: str | None = '54234fafb85a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrichments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('language_confidence', sa.Float(), nullable=True),
    sa.Column('is_relevant', sa.Boolean(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('near_duplicate_of', sa.Uuid(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.Enum('NEGATIVE', 'NEUTRAL', 'POSITIVE', name='sentimentlabel'), nullable=True),
    sa.Column('intent', sa.Enum('FEATURE_REQUEST', 'BUG_REPORT', 'PRAISE', 'COMPLAINT', 'QUESTION', 'CHURN_SIGNAL', 'PRICING', 'COMPETITOR_MENTION', 'SPAM', name='intent'), nullable=True),
    sa.Column('intent_confidence', sa.Float(), nullable=True),
    sa.Column('llm_provider', sa.String(), nullable=True),
    sa.Column('llm_model', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('model_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enriched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_enrichments_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrichments')),
    sa.UniqueConstraint('document_id', name='uq_enrichments_document_id')
    )
    op.create_index(op.f('ix_enrichments_document_id'), 'enrichments', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f('ix_enrichments_document_id'), table_name='enrichments')
    op.drop_table('enrichments')
    sa.Enum(name='sentimentlabel').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='intent').drop(op.get_bind(), checkfirst=True)
