"""add insights, judgements, and generation skips

Revision ID: ad4e27d47757
Revises: 514988dc35b2
Create Date: 2026-08-21 02:25:55.877608+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ad4e27d47757'
down_revision: str | None = '514988dc35b2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_skips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('reason', sa.Enum('DAY_UNTRUSTWORTHY', 'EVIDENCE_TOO_THIN', 'NO_CHANGE_DETECTED', 'GENERATION_FAILED', name='skipreason'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('fk_generation_skips_monitor_id_monitors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_generation_skips_topic_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_skips'))
    )
    op.create_index(op.f('ix_generation_skips_monitor_id'), 'generation_skips', ['monitor_id'], unique=False)
    op.create_index(op.f('ix_generation_skips_topic_id'), 'generation_skips', ['topic_id'], unique=False)
    op.create_table('insights',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('kind', sa.Enum('DIGEST', 'OPPORTUNITY', name='insightkind'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('who', sa.String(), nullable=True),
    sa.Column('what', sa.String(), nullable=True),
    sa.Column('why', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('score_components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('llm_provider', sa.String(), nullable=False),
    sa.Column('llm_model', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('fk_insights_monitor_id_monitors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_insights_topic_id_topics'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insights'))
    )
    op.create_index(op.f('ix_insights_monitor_id'), 'insights', ['monitor_id'], unique=False)
    op.create_index(op.f('ix_insights_topic_id'), 'insights', ['topic_id'], unique=False)
    op.create_index('uq_insights_digest_identity', 'insights', ['monitor_id', 'period_start', 'period_end', 'kind'], unique=True, postgresql_where='topic_id IS NULL')
    op.create_index('uq_insights_topic_identity', 'insights', ['monitor_id', 'topic_id', 'period_start', 'period_end', 'kind'], unique=True, postgresql_where='topic_id IS NOT NULL')
    op.create_table('judgements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('insight_id', sa.Uuid(), nullable=False),
    sa.Column('useful', sa.Boolean(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], name=op.f('fk_judgements_insight_id_insights'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_judgements'))
    )
    op.create_index(op.f('ix_judgements_insight_id'), 'judgements', ['insight_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_judgements_insight_id'), table_name='judgements')
    op.drop_table('judgements')
    op.drop_index('uq_insights_topic_identity', table_name='insights', postgresql_where='topic_id IS NOT NULL')
    op.drop_index('uq_insights_digest_identity', table_name='insights', postgresql_where='topic_id IS NULL')
    op.drop_index(op.f('ix_insights_topic_id'), table_name='insights')
    op.drop_index(op.f('ix_insights_monitor_id'), table_name='insights')
    op.drop_table('insights')
    op.drop_index(op.f('ix_generation_skips_topic_id'), table_name='generation_skips')
    op.drop_index(op.f('ix_generation_skips_monitor_id'), table_name='generation_skips')
    op.drop_table('generation_skips')
    # ### end Alembic commands ###
    sa.Enum(name='insightkind').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='skipreason').drop(op.get_bind(), checkfirst=True)
