"""add daily metrics table

Revision ID: 3b6f2dc4891d
Revises: 531c2b9e63df
Create Date: 2026-08-20 10:48:55.105858+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3b6f2dc4891d'
down_revision: str | None = '531c2b9e63df'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('bucket', sa.Date(), nullable=False),
    sa.Column('source_name', postgresql.ENUM('PLAY', 'APPSTORE', 'DISCOURSE', 'NEWS', 'RSS', 'HACKERNEWS', name='sourcename', create_type=False), nullable=True),
    sa.Column('topic_id', sa.Uuid(), nullable=True),
    sa.Column('doc_count', sa.Integer(), nullable=False),
    sa.Column('doc_count_share', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('quota_hit', sa.Boolean(), nullable=False),
    sa.Column('sentiment_mean', sa.Float(), nullable=True),
    sa.Column('sentiment_p25', sa.Float(), nullable=True),
    sa.Column('negativity_rate', sa.Float(), nullable=True),
    sa.Column('engagement_sum', sa.Integer(), nullable=True),
    sa.Column('author_diversity', sa.Float(), nullable=True),
    sa.Column('rating_mean', sa.Float(), nullable=True),
    sa.Column('intent_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Enum('SCHEDULED', 'LATE_ARRIVAL', 'TOPIC_MERGE', 'MANUAL', name='rollupreason'), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('fk_daily_metrics_monitor_id_monitors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_daily_metrics_topic_id_topics'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_metrics'))
    )
    op.create_index(op.f('ix_daily_metrics_bucket'), 'daily_metrics', ['bucket'], unique=False)
    op.create_index(op.f('ix_daily_metrics_monitor_id'), 'daily_metrics', ['monitor_id'], unique=False)
    op.create_index(op.f('ix_daily_metrics_topic_id'), 'daily_metrics', ['topic_id'], unique=False)
    # Range queries over one monitor's date span are the read pattern every
    # later consumer (metrics-read-api, trend-detection) needs.
    op.create_index(
        'ix_daily_metrics_monitor_bucket', 'daily_metrics', ['monitor_id', 'bucket'], unique=False
    )
    # A plain UNIQUE constraint would let two "all sources" rows for the same
    # (monitor, bucket, topic) coexist, since SQL never considers two NULLs
    # equal. An enum column cannot be cast inside an index expression
    # (Postgres requires IMMUTABLE, and an enum's ordering is catalog-
    # dependent), so uniqueness across the all-value case (design.md,
    # "Domain shapes": MetricKey's all-value admission) is four partial
    # indexes instead, one per nullability combination, rather than one
    # expression index.
    op.execute(
        "CREATE UNIQUE INDEX uq_daily_metrics_key_both ON daily_metrics "
        "(monitor_id, bucket, source_name, topic_id) "
        "WHERE source_name IS NOT NULL AND topic_id IS NOT NULL"
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_daily_metrics_key_source_only ON daily_metrics "
        "(monitor_id, bucket, source_name) "
        "WHERE source_name IS NOT NULL AND topic_id IS NULL"
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_daily_metrics_key_topic_only ON daily_metrics "
        "(monitor_id, bucket, topic_id) "
        "WHERE source_name IS NULL AND topic_id IS NOT NULL"
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_daily_metrics_key_neither ON daily_metrics "
        "(monitor_id, bucket) "
        "WHERE source_name IS NULL AND topic_id IS NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS uq_daily_metrics_key_neither")
    op.execute("DROP INDEX IF EXISTS uq_daily_metrics_key_topic_only")
    op.execute("DROP INDEX IF EXISTS uq_daily_metrics_key_source_only")
    op.execute("DROP INDEX IF EXISTS uq_daily_metrics_key_both")
    op.drop_index('ix_daily_metrics_monitor_bucket', table_name='daily_metrics')
    op.drop_index(op.f('ix_daily_metrics_topic_id'), table_name='daily_metrics')
    op.drop_index(op.f('ix_daily_metrics_monitor_id'), table_name='daily_metrics')
    op.drop_index(op.f('ix_daily_metrics_bucket'), table_name='daily_metrics')
    op.drop_table('daily_metrics')
    sa.Enum(name='rollupreason').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
