"""add discovery outcomes and relevance basis

Revision ID: 29e437134133
Revises: 08c095061878
Create Date: 2026-08-21 12:14:45.023834+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '29e437134133'
down_revision: str | None = '08c095061878'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovery_outcomes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('queries_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('proposed', sa.Integer(), nullable=False),
    sa.Column('rejected_known', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('NO_QUERIES', 'EVERY_SURFACE_EMPTY', name='nodiscoveryreason'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('fk_discovery_outcomes_monitor_id_monitors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discovery_outcomes'))
    )
    op.create_index(op.f('ix_discovery_outcomes_monitor_id'), 'discovery_outcomes', ['monitor_id'], unique=False)
    # add_column with a bare sa.Enum does not auto-create the Postgres type
    # the way create_table does, so it is created explicitly first.
    sa.Enum('DESCRIPTION', 'QUERIES', 'CORPUS_CENTROID', name='relevancebasis').create(
        op.get_bind(), checkfirst=True
    )
    op.add_column('enrichments', sa.Column('relevance_basis', postgresql.ENUM('DESCRIPTION', 'QUERIES', 'CORPUS_CENTROID', name='relevancebasis', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrichments', 'relevance_basis')
    op.drop_index(op.f('ix_discovery_outcomes_monitor_id'), table_name='discovery_outcomes')
    op.drop_table('discovery_outcomes')
    # ### end Alembic commands ###
    sa.Enum(name='relevancebasis').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='nodiscoveryreason').drop(op.get_bind(), checkfirst=True)
