"""add theme jobs

Revision ID: bba35b6d27f5
Revises: 02b914861883
Create Date: 2026-08-27 05:39:21.929423+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'bba35b6d27f5'
down_revision: str | None = '02b914861883'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theme_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('QUERY_GENERATION', 'DISCOVERY', name='themejobkind'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETE', 'FAILED', name='themejobstatus'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('fk_theme_jobs_monitor_id_monitors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_theme_jobs'))
    )
    op.create_index(op.f('ix_theme_jobs_monitor_id'), 'theme_jobs', ['monitor_id'], unique=False)
    # ### end Alembic commands ###
    # ix_topics_centroid_hnsw is not declared on the ORM model, so autogenerate
    # proposed dropping it as drift; that index is out of scope for this
    # migration and is left alone.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_theme_jobs_monitor_id'), table_name='theme_jobs')
    op.drop_table('theme_jobs')
    # ### end Alembic commands ###
