"""create monitors and schedule registrations

Revision ID: bb7bcdc81dac
Revises: 
Create Date: 2026-08-19 12:06:40.231340+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'bb7bcdc81dac'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target_type', sa.Enum('PRODUCT', 'THEME', name='targettype'), nullable=False),
    sa.Column('seed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'ARCHIVED', name='monitorstatus'), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monitors'))
    )
    op.create_table('schedule_registrations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('cron_expression', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('fk_schedule_registrations_monitor_id_monitors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_registrations')),
    sa.UniqueConstraint('monitor_id', name='uq_schedule_registrations_monitor_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('schedule_registrations')
    op.drop_table('monitors')
    # DROP TABLE leaves the enum types behind: nothing references them, but
    # Postgres does not drop a type just because its last column is gone.
    sa.Enum(name='monitorstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='targettype').drop(op.get_bind(), checkfirst=True)
