"""add label sets, labels, snapshots, and reports

Revision ID: 88bd224b2b63
Revises: 5e735171dc5f
Create Date: 2026-08-21 05:19:31.987187+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '88bd224b2b63'
down_revision: str | None = '5e735171dc5f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label_sets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.Enum('RELEVANCE', 'EVENTS', name='purpose'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('fk_label_sets_monitor_id_monitors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_label_sets'))
    )
    op.create_index(op.f('ix_label_sets_monitor_id'), 'label_sets', ['monitor_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('measures', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config_fingerprint', sa.String(), nullable=False),
    sa.Column('code_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('fk_reports_monitor_id_monitors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_monitor_id'), 'reports', ['monitor_id'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('taken_on', sa.Date(), nullable=False),
    sa.Column('assignments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('fk_snapshots_monitor_id_monitors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_snapshots')),
    sa.UniqueConstraint('monitor_id', 'taken_on', name='uq_snapshots_monitor_taken_on')
    )
    op.create_index(op.f('ix_snapshots_monitor_id'), 'snapshots', ['monitor_id'], unique=False)
    op.create_table('document_labels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('label_set_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('is_relevant', sa.Boolean(), nullable=False),
    sa.Column('labelled_by', sa.String(), nullable=False),
    sa.Column('labelled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_labels_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['label_set_id'], ['label_sets.id'], name=op.f('fk_document_labels_label_set_id_label_sets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_labels'))
    )
    op.create_index(op.f('ix_document_labels_document_id'), 'document_labels', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_labels_label_set_id'), 'document_labels', ['label_set_id'], unique=False)
    op.create_table('event_labels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('label_set_id', sa.Uuid(), nullable=False),
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('external_reference', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['label_set_id'], ['label_sets.id'], name=op.f('fk_event_labels_label_set_id_label_sets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('fk_event_labels_monitor_id_monitors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_labels'))
    )
    op.create_index(op.f('ix_event_labels_label_set_id'), 'event_labels', ['label_set_id'], unique=False)
    op.create_index(op.f('ix_event_labels_monitor_id'), 'event_labels', ['monitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_labels_monitor_id'), table_name='event_labels')
    op.drop_index(op.f('ix_event_labels_label_set_id'), table_name='event_labels')
    op.drop_table('event_labels')
    op.drop_index(op.f('ix_document_labels_label_set_id'), table_name='document_labels')
    op.drop_index(op.f('ix_document_labels_document_id'), table_name='document_labels')
    op.drop_table('document_labels')
    op.drop_index(op.f('ix_snapshots_monitor_id'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_reports_monitor_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_label_sets_monitor_id'), table_name='label_sets')
    op.drop_table('label_sets')
    # ### end Alembic commands ###
    sa.Enum(name='purpose').drop(op.get_bind(), checkfirst=True)
