"""add topics, assignments, lineage, and split proposals

Revision ID: 531c2b9e63df
Revises: 652958fbb901
Create Date: 2026-08-20 06:08:37.966302+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '531c2b9e63df'
down_revision: str | None = '652958fbb901'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('centroid', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('doc_count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.Date(), nullable=False),
    sa.Column('last_seen', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DORMANT', 'MERGED', 'ARCHIVED', name='topicstatus'), nullable=False),
    sa.Column('merged_into', sa.Uuid(), nullable=True),
    sa.Column('drift_score', sa.Float(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('label_is_provisional', sa.Boolean(), nullable=False),
    sa.Column('label_provider', sa.String(), nullable=True),
    sa.Column('label_model', sa.String(), nullable=True),
    sa.Column('label_prompt_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merged_into'], ['topics.id'], name=op.f('fk_topics_merged_into_topics'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('fk_topics_monitor_id_monitors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics'))
    )
    op.create_index(op.f('ix_topics_monitor_id'), 'topics', ['monitor_id'], unique=False)
    op.execute(
        "CREATE INDEX ix_topics_centroid_hnsw ON topics "
        "USING hnsw (centroid vector_cosine_ops)"
    )
    op.create_table('assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('method', sa.Enum('CENTROID', 'CLUSTERED', 'MANUAL', name='assignmentmethod'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_assignments_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_assignments_topic_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignments')),
    sa.UniqueConstraint('document_id', name='uq_assignments_document_id')
    )
    op.create_index(op.f('ix_assignments_document_id'), 'assignments', ['document_id'], unique=False)
    op.create_index(op.f('ix_assignments_topic_id'), 'assignments', ['topic_id'], unique=False)
    op.create_table('lineage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_topic', sa.Uuid(), nullable=False),
    sa.Column('to_topic', sa.Uuid(), nullable=True),
    sa.Column('event', sa.Enum('MERGE', 'REFIT_REMAP', 'SPLIT_PROPOSED', name='lineageevent'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['from_topic'], ['topics.id'], name=op.f('fk_lineage_from_topic_topics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_topic'], ['topics.id'], name=op.f('fk_lineage_to_topic_topics'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lineage'))
    )
    op.create_index(op.f('ix_lineage_from_topic'), 'lineage', ['from_topic'], unique=False)
    op.create_table('split_proposals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('evidence', sa.String(), nullable=False),
    sa.Column('drift_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'DISMISSED', name='splitproposalstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_split_proposals_topic_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_split_proposals'))
    )
    op.create_index(op.f('ix_split_proposals_topic_id'), 'split_proposals', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_split_proposals_topic_id'), table_name='split_proposals')
    op.drop_table('split_proposals')
    op.drop_index(op.f('ix_lineage_from_topic'), table_name='lineage')
    op.drop_table('lineage')
    op.drop_index(op.f('ix_assignments_topic_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_document_id'), table_name='assignments')
    op.drop_table('assignments')
    op.execute("DROP INDEX IF EXISTS ix_topics_centroid_hnsw")
    op.drop_index(op.f('ix_topics_monitor_id'), table_name='topics')
    op.drop_table('topics')
    # ### end Alembic commands ###
    # DROP TABLE leaves these enum types behind: nothing references them
    # afterward, but Postgres does not drop a type just because its last
    # column is gone (same issue fixed in earlier migrations).
    sa.Enum(name='splitproposalstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='lineageevent').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='assignmentmethod').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='topicstatus').drop(op.get_bind(), checkfirst=True)
