"""add stage status to ingestion runs

Revision ID: 414a793e33c0
Revises: 0218dd7f6663
Create Date: 2026-08-20 00:27:59.989086+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '414a793e33c0'
down_revision: str | None = '0218dd7f6663'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestion_runs', sa.Column('stage_status', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestion_runs', 'stage_status')
    # ### end Alembic commands ###
