"""add alert rules and deliveries

Revision ID: 5e735171dc5f
Revises: ad4e27d47757
Create Date: 2026-08-21 04:13:44.994984+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5e735171dc5f'
down_revision: str | None = 'ad4e27d47757'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('PRODUCT', 'SCRAPER', name='readalertkind'), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'WEBHOOK', name='channel'), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('fk_alert_rules_monitor_id_monitors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_rules'))
    )
    op.create_index(op.f('ix_alert_rules_monitor_id'), 'alert_rules', ['monitor_id'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('state', sa.Enum('PENDING', 'DELIVERED', 'FAILED', 'ABANDONED', name='deliverystate'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], name=op.f('fk_deliveries_rule_id_alert_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deliveries'))
    )
    op.create_index(op.f('ix_deliveries_rule_id'), 'deliveries', ['rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deliveries_rule_id'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_alert_rules_monitor_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
    sa.Enum(name='deliverystate').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='channel').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='readalertkind').drop(op.get_bind(), checkfirst=True)
