"""add sources, ingestion runs, stats, and documents

Revision ID: 0218dd7f6663
Revises: 131f6c8e5ead
Create Date: 2026-08-19 14:16:13.204937+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0218dd7f6663'
down_revision: str | None = '131f6c8e5ead'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('source_name', sa.Enum('PLAY', 'APPSTORE', 'DISCOURSE', 'NEWS', 'RSS', 'HACKERNEWS', name='sourcename'), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('author_hash', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('app_version', sa.String(), nullable=True),
    sa.Column('engagement', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('fk_documents_monitor_id_monitors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('monitor_id', 'source_name', 'external_id', name='uq_documents_natural_key')
    )
    op.create_index(op.f('ix_documents_monitor_id'), 'documents', ['monitor_id'], unique=False)
    op.create_index(op.f('ix_documents_published_at'), 'documents', ['published_at'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('is_backfill', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PARTIAL', 'COMPLETE', 'FAILED', name='runstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('fk_ingestion_runs_monitor_id_monitors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_runs')),
    sa.UniqueConstraint('monitor_id', 'run_date', 'is_backfill', name='uq_ingestion_runs_identity')
    )
    op.create_index(op.f('ix_ingestion_runs_monitor_id'), 'ingestion_runs', ['monitor_id'], unique=False)
    op.create_table('monitor_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('source_name', sa.Enum('PLAY', 'APPSTORE', 'DISCOURSE', 'NEWS', 'RSS', 'HACKERNEWS', name='sourcename'), nullable=False),
    sa.Column('instance_key', sa.String(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('daily_quota', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_external_id', sa.String(), nullable=True),
    sa.Column('last_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('fk_monitor_sources_monitor_id_monitors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monitor_sources')),
    sa.UniqueConstraint('monitor_id', 'source_name', 'instance_key', name='uq_monitor_sources_identity')
    )
    op.create_index(op.f('ix_monitor_sources_monitor_id'), 'monitor_sources', ['monitor_id'], unique=False)
    op.create_table('fetch_stats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('monitor_source_id', sa.Uuid(), nullable=False),
    sa.Column('attempted', sa.Integer(), nullable=False),
    sa.Column('fetched', sa.Integer(), nullable=False),
    sa.Column('duplicates', sa.Integer(), nullable=False),
    sa.Column('kept', sa.Integer(), nullable=False),
    sa.Column('quota', sa.Integer(), nullable=False),
    sa.Column('quota_outcome', sa.Enum('WITHIN_ALLOWANCE', 'ALLOWANCE_REACHED', name='quotaoutcome'), nullable=False),
    sa.Column('validation_failed', sa.Boolean(), nullable=False),
    sa.Column('library_version', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['monitor_source_id'], ['monitor_sources.id'], name=op.f('fk_fetch_stats_monitor_source_id_monitor_sources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], name=op.f('fk_fetch_stats_run_id_ingestion_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fetch_stats')),
    sa.UniqueConstraint('run_id', 'monitor_source_id', name='uq_fetch_stats_run_source')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('fetch_stats')
    op.drop_index(op.f('ix_monitor_sources_monitor_id'), table_name='monitor_sources')
    op.drop_table('monitor_sources')
    op.drop_index(op.f('ix_ingestion_runs_monitor_id'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_documents_published_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_monitor_id'), table_name='documents')
    op.drop_table('documents')
    # DROP TABLE leaves these enum types behind (same issue fixed in the
    # monitor-registry migration): nothing references them afterward, but
    # Postgres does not drop a type just because its last column is gone.
    sa.Enum(name='quotaoutcome').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='runstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='sourcename').drop(op.get_bind(), checkfirst=True)
