"""add trend events, gate outcomes, and trend scores

Revision ID: 514988dc35b2
Revises: 3b6f2dc4891d
Create Date: 2026-08-21 00:56:52.658093+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '514988dc35b2'
down_revision: str | None = '3b6f2dc4891d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gate_outcomes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('bucket', sa.Date(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Enum('BELOW_VOLUME_FLOOR', 'INSUFFICIENT_BASELINE', 'COOLDOWN_ACTIVE', 'CORRECTED_AWAY', 'DAY_UNTRUSTWORTHY', name='gatereason'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('fk_gate_outcomes_monitor_id_monitors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_gate_outcomes_topic_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gate_outcomes'))
    )
    op.create_index(op.f('ix_gate_outcomes_bucket'), 'gate_outcomes', ['bucket'], unique=False)
    op.create_index(op.f('ix_gate_outcomes_monitor_id'), 'gate_outcomes', ['monitor_id'], unique=False)
    op.create_index(op.f('ix_gate_outcomes_topic_id'), 'gate_outcomes', ['topic_id'], unique=False)
    op.create_table('trend_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('detected_on', sa.Date(), nullable=False),
    sa.Column('kind', sa.Enum('BURST', 'SUSTAINED_GROWTH', 'DECLINE', 'SENTIMENT_FLIP', 'CHANGEPOINT', 'EMERGENCE', 'NOVELTY', name='eventkind'), nullable=False),
    sa.Column('method', sa.Enum('ROBUST_Z', 'POISSON_EXACT', 'KLEINBERG', 'MANN_KENDALL', 'PELT', 'CTFIDF_DELTA', name='detectionmethod'), nullable=False),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('statistics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('fk_trend_events_monitor_id_monitors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_trend_events_topic_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trend_events')),
    sa.UniqueConstraint('monitor_id', 'topic_id', 'detected_on', 'kind', name='uq_trend_events_identity')
    )
    op.create_index(op.f('ix_trend_events_detected_on'), 'trend_events', ['detected_on'], unique=False)
    op.create_index(op.f('ix_trend_events_monitor_id'), 'trend_events', ['monitor_id'], unique=False)
    op.create_index(op.f('ix_trend_events_topic_id'), 'trend_events', ['topic_id'], unique=False)
    op.create_table('trend_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('bucket', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('penalties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('withheld_reason', sa.String(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('fk_trend_scores_monitor_id_monitors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_trend_scores_topic_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trend_scores')),
    sa.UniqueConstraint('monitor_id', 'topic_id', 'bucket', name='uq_trend_scores_identity')
    )
    op.create_index(op.f('ix_trend_scores_bucket'), 'trend_scores', ['bucket'], unique=False)
    op.create_index(op.f('ix_trend_scores_monitor_id'), 'trend_scores', ['monitor_id'], unique=False)
    op.create_index(op.f('ix_trend_scores_topic_id'), 'trend_scores', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trend_scores_topic_id'), table_name='trend_scores')
    op.drop_index(op.f('ix_trend_scores_monitor_id'), table_name='trend_scores')
    op.drop_index(op.f('ix_trend_scores_bucket'), table_name='trend_scores')
    op.drop_table('trend_scores')
    op.drop_index(op.f('ix_trend_events_topic_id'), table_name='trend_events')
    op.drop_index(op.f('ix_trend_events_monitor_id'), table_name='trend_events')
    op.drop_index(op.f('ix_trend_events_detected_on'), table_name='trend_events')
    op.drop_table('trend_events')
    op.drop_index(op.f('ix_gate_outcomes_topic_id'), table_name='gate_outcomes')
    op.drop_index(op.f('ix_gate_outcomes_monitor_id'), table_name='gate_outcomes')
    op.drop_index(op.f('ix_gate_outcomes_bucket'), table_name='gate_outcomes')
    op.drop_table('gate_outcomes')
    # ### end Alembic commands ###
    sa.Enum(name='detectionmethod').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='eventkind').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='gatereason').drop(op.get_bind(), checkfirst=True)
