"""add theme seeds and entity candidates

Revision ID: 08c095061878
Revises: 88bd224b2b63
Create Date: 2026-08-21 12:06:03.560321+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '08c095061878'
down_revision: str | None = '88bd224b2b63'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('source_name', postgresql.ENUM('PLAY', 'APPSTORE', 'DISCOURSE', 'NEWS', 'RSS', 'HACKERNEWS', name='sourcename', create_type=False), nullable=False),
    sa.Column('entity_ref', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('proposed_by_query', sa.String(), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', sa.Enum('PROPOSED', 'ACCEPTED', 'REJECTED', name='candidatestate'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('fk_entity_candidates_monitor_id_monitors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_candidates')),
    sa.UniqueConstraint('monitor_id', 'source_name', 'entity_ref', name='uq_entity_candidates_identity')
    )
    op.create_index(op.f('ix_entity_candidates_monitor_id'), 'entity_candidates', ['monitor_id'], unique=False)
    op.create_table('theme_seeds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('queries', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('fk_theme_seeds_monitor_id_monitors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_theme_seeds')),
    sa.UniqueConstraint('monitor_id', name='uq_theme_seeds_monitor_id')
    )
    op.create_index(op.f('ix_theme_seeds_monitor_id'), 'theme_seeds', ['monitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_theme_seeds_monitor_id'), table_name='theme_seeds')
    op.drop_table('theme_seeds')
    op.drop_index(op.f('ix_entity_candidates_monitor_id'), table_name='entity_candidates')
    op.drop_table('entity_candidates')
    # ### end Alembic commands ###
    sa.Enum(name='candidatestate').drop(op.get_bind(), checkfirst=True)
