"""add override jobs

Revision ID: 02b914861883
Revises: 29e437134133
Create Date: 2026-08-22 11:40:42.859304+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '02b914861883'
down_revision: str | None = '29e437134133'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('override_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('STAGE_RERUN', 'BACKFILL_WINDOW', 'RETENTION_PURGE', name='overridekind'), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETE', 'PARTIAL', 'FAILED', name='overridestatus'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('fk_override_jobs_monitor_id_monitors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_override_jobs'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('override_jobs')
    sa.Enum(name='overridestatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='overridekind').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
