"""add source health, alerts, and backfill jobs

Revision ID: 54234fafb85a
Revises: 414a793e33c0
Create Date: 2026-08-20 02:17:38.481389+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '54234fafb85a'
down_revision: str | None = '414a793e33c0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backfill_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('window_start', sa.Date(), nullable=False),
    sa.Column('window_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETE', 'FAILED', name='backfillstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('fk_backfill_jobs_monitor_id_monitors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backfill_jobs'))
    )
    op.create_table('scraper_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('monitor_source_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('EMPTY_STREAK', 'VOLUME_COLLAPSE', 'SMOKE_FAILED', 'LIBRARY_STALE', name='alertkind'), nullable=False),
    sa.Column('raised_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('observed', sa.String(), nullable=True),
    sa.Column('expected', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('fk_scraper_alerts_monitor_id_monitors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monitor_source_id'], ['monitor_sources.id'], name=op.f('fk_scraper_alerts_monitor_source_id_monitor_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scraper_alerts'))
    )
    op.create_table('source_health',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monitor_source_id', sa.Uuid(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_empty', sa.Integer(), nullable=False),
    sa.Column('consecutive_fail', sa.Integer(), nullable=False),
    sa.Column('rows_median_28d', sa.Float(), nullable=True),
    sa.Column('library_version', sa.String(), nullable=True),
    sa.Column('state', sa.Enum('HEALTHY', 'DEGRADED', 'BROKEN', 'DISABLED', name='sourcestate'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['monitor_source_id'], ['monitor_sources.id'], name=op.f('fk_source_health_monitor_source_id_monitor_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_health')),
    sa.UniqueConstraint('monitor_source_id', name='uq_source_health_monitor_source_id')
    )
    fetch_outcome_kind = sa.Enum('COLLECTED', 'FAILED', 'SKIPPED_DISABLED', name='fetchoutcomekind')
    fetch_outcome_kind.create(op.get_bind())
    op.add_column(
        'fetch_stats',
        sa.Column(
            'outcome_kind', fetch_outcome_kind, nullable=False, server_default='COLLECTED'
        ),
    )
    op.alter_column('fetch_stats', 'outcome_kind', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column('fetch_stats', 'outcome_kind')
    op.drop_table('source_health')
    op.drop_table('scraper_alerts')
    op.drop_table('backfill_jobs')
    sa.Enum(name='fetchoutcomekind').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='sourcestate').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='alertkind').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='backfillstatus').drop(op.get_bind(), checkfirst=True)
